---
kind: pipeline
type: kubernetes
name: Kube-Builder-windows-amd64

platform:
  os: windows
  arch: amd64

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      dockerfile: ./Dockerfile-windows
      dry_run: true
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT}
        - latest
        - ${DRONE_BUILD_NUMBER}-windows-amd64
        - ${DRONE_COMMIT}-windows-amd64
        - latest-windows-amd64

  - name: Docker-Publish
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      dockerfile: ./Dockerfile-windows
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT}
        - latest
        - ${DRONE_BUILD_NUMBER}-windows-amd64
        - ${DRONE_COMMIT}-windows-amd64
        - latest-windows-amd64
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly

node_selector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: windows
  drone-runner: true