---
kind: pipeline
type: kubernetes
name: Kube-Builder

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      dry_run: true
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest

  - name: Docker-Publish
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly
