---
kind: pipeline
type: kubernetes
name: Kube-Builder-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      dry_run: true
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT}
        - latest
        - ${DRONE_BUILD_NUMBER}-linux-arm64
        - ${DRONE_COMMIT}-linux-arm64
        - latest-linux-arm64

  - name: Docker-Publish
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT}
        - latest
        - ${DRONE_BUILD_NUMBER}-linux-arm64
        - ${DRONE_COMMIT}-linux-arm64
        - latest-linux-arm64
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly

node_selector:
  kubernetes.io/arch: arm64
  kubernetes.io/os: linux
  drone-runner: true