---
kind: pipeline
type: kubernetes
name: Kube-Builder

steps:
  - name: docker-build-npd
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      tags:
        - pr-${DRONE_BUILD_NUMBER}
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
      branch:
      - feature/*

  - name: docker-build-prd
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
      branch:
      - master
