---
kind: pipeline
type: docker
name: SupportTools-Kube-Builder

steps:
  - name: build-docker
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      tags:
        - pr-${DRONE_BUILD_NUMBER}
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
