---
kind: pipeline
type: docker
name: Kube-Builder

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Docker Build - linux/amd64
  image: maniator/docker-with-buildx
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker version
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --use
  - docker buildx build --platform linux/amd64 -t supporttools/kube-builder:latest -t supporttools/kube-builder:${DRONE_BUILD_NUMBER} -t supporttools/kube-builder:$DRONE_COMMIT_SHA -f Dockerfile.AMD64 .

- name: Docker Build - linux/arm64
  image: maniator/docker-with-buildx
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker version
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --use
  - docker buildx build --platform linux/arm64,linux/arm/v7 -t supporttools/kube-builder:latest -t supporttools/kube-builder:${DRONE_BUILD_NUMBER} -t supporttools/kube-builder:$DRONE_COMMIT_SHA -f Dockerfile.ARM64 .

- name: Docker Publish - linux/amd64
  image: maniator/docker-with-buildx
  environment:
    DOCKER_USERNAME:
      from_secret: docker-username
    DOCKER_PASSWORD:
      from_secret: docker-password
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker version
  - docker buildx version
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --use
  - docker buildx build --platform linux/amd64 -t supporttools/kube-builder:latest -t supporttools/kube-builder:${DRONE_BUILD_NUMBER} -t supporttools/kube-builder:$DRONE_COMMIT_SHA --push -f -f Dockerfile.AMD64.
  when:
    event:
    - deployment
    - promote
    - cron
    target:
    - production
    - weekly

- name: Docker Publish - linux/arm64
  image: maniator/docker-with-buildx
  environment:
    DOCKER_USERNAME:
      from_secret: docker-username
    DOCKER_PASSWORD:
      from_secret: docker-password
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker version
  - docker buildx version
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --use
  - docker buildx build --platform linux/arm64,linux/arm/v7 -t supporttools/kube-builder:latest -t supporttools/kube-builder:${DRONE_BUILD_NUMBER} -t supporttools/kube-builder:$DRONE_COMMIT_SHA --push -f Dockerfile.ARM64 .
  when:
    event:
    - deployment
    - promote
    - cron
    target:
    - production
    - weekly

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
