---
kind: pipeline
type: kubernetes
name: Kube-Builder

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
