---
kind: pipeline
type: docker
name: Kube-Builder

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

environment:
  DOCKER_HOST: tcp://docker-in-docker:2375
  DOCKER_CLI_EXPERIMENTAL: enabled

steps:
- name: Docker Build - linux/amd64
  image: ncrmro/docker-buildx:19.03.10
  commands:
  - docker version
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --use
  - docker buildx build --platform linux/amd64 -t supporttools/kube-builder:latest -t supporttools/kube-builder:${DRONE_BUILD_NUMBER} -t supporttools/kube-builder:$DRONE_COMMIT_SHA -f Dockerfile.AMD64 .

- name: Docker Build - linux/arm64
  image: ncrmro/docker-buildx:19.03.10
  commands:
  - docker version
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --use
  - docker buildx build --platform linux/arm64,linux/arm/v6,linux/arm/v7 -t supporttools/kube-builder:latest -t supporttools/kube-builder:${DRONE_BUILD_NUMBER} -t supporttools/kube-builder:$DRONE_COMMIT_SHA -f Dockerfile.ARM64 .


- name: Docker Publish - linux/amd64
  image: ncrmro/docker-buildx:19.03.10
  environment:
    DOCKER_USERNAME:
      from_secret: docker-username
    DOCKER_PASSWORD:
      from_secret: docker-password
  commands:
  - docker version
  - docker buildx version
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --use
  - docker buildx build --platform linux/amd64 -t supporttools/kube-builder:latest -t supporttools/kube-builder:${DRONE_BUILD_NUMBER} -t supporttools/kube-builder:$DRONE_COMMIT_SHA --push -f -f Dockerfile.AMD64.
  when:
    event:
    - deployment
    - promote
    - cron
    target:
    - production
    - weekly

- name: Docker Publish - linux/arm64
  image: ncrmro/docker-buildx:19.03.10
  environment:
    DOCKER_USERNAME:
      from_secret: docker-username
    DOCKER_PASSWORD:
      from_secret: docker-password
  commands:
  - docker version
  - docker buildx version
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch --use
  - docker buildx build --platform linux/arm64,linux/arm/v6,linux/arm/v7 -t supporttools/kube-builder:latest -t supporttools/kube-builder:${DRONE_BUILD_NUMBER} -t supporttools/kube-builder:$DRONE_COMMIT_SHA --push -f Dockerfile.ARM64 .
  when:
    event:
    - deployment
    - promote
    - cron
    target:
    - production
    - weekly

services:
- name: docker-in-docker
  docker:
  image: docker:19.03.12-dind
  command: ["dockerd", "--host", "0.0.0.0", "--experimental"]
  privileged: true

node_selector:
  beta.kubernetes.io/arch: amd64
  drone-runner: true