---
kind: pipeline
type: vm
name: Kube-Builder

concurrency:
  limit: 1

steps:
- name: Docker Build
  image: cube8021/docker-buildx:20.10.14-0.8.2
  commands:
  - sh ./docker-build.sh  
  when:
    event:
      exclude:
      - deployment
      - promote
      - cron

- name: Docker Publish
  image: cube8021/docker-buildx:20.10.14-0.8.2
  environment:
    DOCKER_USERNAME:
      from_secret: docker-username
    DOCKER_PASSWORD:
      from_secret: docker-password
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - sh ./docker-build.sh push
  when:
    event:
    - deployment
    - promote
    - cron
    target:
    - production
    - weekly