---
kind: pipeline
type: docker
name: Kube-Builder

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

concurrency:
  limit: 1

environment:
  DOCKER_HOST: tcp://docker-in-docker:2375
  DOCKER_CLI_EXPERIMENTAL: enabled

steps:
- name: Docker Build
  image: cube8021/docker-buildx:20.10.14-0.8.2
  commands:
  - sh ./docker-build.sh  
  when:
    event:
      exclude:
      - deployment
      - promote
      - cron

- name: Docker Publish
  image: cube8021/docker-buildx:20.10.14-0.8.2
  environment:
    DOCKER_USERNAME:
      from_secret: docker-username
    DOCKER_PASSWORD:
      from_secret: docker-password
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - sh ./docker-build.sh push
  when:
    event:
    - deployment
    - promote
    - cron
    target:
    - production
    - weekly

services:
- name: docker-in-docker
  docker:
  image: docker:20.10.14-dind
  command: ["dockerd", "--host", "0.0.0.0", "--experimental", "--dns", "8.8.8.8", "--dns", "8.8.4.4"]
  privileged: true
