---
kind: pipeline
type: docker
name: Kube-Builder

platform:
  os: linux
  arch: amd64

steps:
  - name: Docker-Build
    image: plugins/docker
    custom_dns: [ 172.27.2.2.23, 172.27.2.23 ]
    settings:
      repo: supporttools/kube-builder
      dry_run: true
      purge: false
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT}
        - latest

  - name: Docker-Publish
    image: plugins/docker
    custom_dns: [ 172.27.2.2.23, 172.27.2.23 ]
    settings:
      repo: supporttools/kube-builder
      purge: false
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly