---
kind: pipeline
type: docker
name: Docker-Build-AMD64

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      dry_run: true
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT}
        - latest

  - name: Docker-Publish
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT}
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly