---
kind: pipeline
type: docker
name: Docker-Build-AMD64

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      dry_run: true
      purge: false
      dockerfile: Dockerfile.AMD64
      tags:
        - ${DRONE_BUILD_NUMBER}-amd64
        - ${DRONE_COMMIT}-amd64
        - latest-amd64
        - latest

  - name: Docker-Publish-Hub
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      purge: false
      dockerfile: Dockerfile.AMD64
      tags:
        - ${DRONE_BUILD_NUMBER}-amd64
        - ${DRONE_COMMIT}-amd64
        - latest-amd64
        - latest
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly

  - name: Docker-Publish-Private
    image: plugins/docker
    settings:
      registry: harbor.support.tools
      repo:  harbor.support.tools/supporttools/kube-builder
      purge: false
      dockerfile: Dockerfile.AMD64
      tags:
        - ${DRONE_BUILD_NUMBER}-amd64
        - ${DRONE_COMMIT}-amd64
        - latest-amd64
        - latest
      username:
        from_secret: harbor-username
      password:
        from_secret: harbor-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly

node_selector:
  beta.kubernetes.io/arch: amd64
  drone-runner: true

---
kind: pipeline
type: docker
name: Docker-Build-ARM64

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      dry_run: true
      purge: false
      dockerfile: Dockerfile.ARM64
      tags:
        - ${DRONE_BUILD_NUMBER}-arm64
        - ${DRONE_COMMIT}-arm64
        - latest-arm64

  - name: Docker-Publish-Hub
    image: plugins/docker
    settings:
      repo: supporttools/kube-builder
      purge: false
      dockerfile: Dockerfile.ARM64
      tags:
        - ${DRONE_BUILD_NUMBER}-arm64
        - ${DRONE_COMMIT}-arm64
        - latest-arm64
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly

  - name: Docker-Publish-Private
    image: plugins/docker
    settings:
      registry: harbor.support.tools
      repo:  harbor.support.tools/supporttools/kube-builder
      purge: false
      dockerfile: Dockerfile.ARM64
      tags:
        - ${DRONE_BUILD_NUMBER}-arm64
        - ${DRONE_COMMIT}-arm64
        - latest-arm64
      username:
        from_secret: harbor-username
      password:
        from_secret: harbor-password
    when:
     event:
     - deployment
     - promote
     - cron
     target:
     - production
     - weekly

node_selector:
  beta.kubernetes.io/arch: amd64
  drone-runner: true
