name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # This will run every day at midnight UTC

jobs:
  Build:
    runs-on: self-hosted-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --pull \
            --cache-from supporttools/kube-builder:latest \
            -t supporttools/kube-builder:v${{ github.run_number }} \
            -t supporttools/kube-builder:latest \
            --push \
            -f Dockerfile .